chore: estruturação inicial do formulário
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #10
Opened 2023-10-27 02:49 UTC by gabrieladnz

2023-10-27 02:50 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] - Componente de formulário](https://trello.com/c/mCUvDz0e/264-front-componente-de-formul%C3%A1rio)

2023-10-27 12:44 UTC, matheus-yudi-newrizon requested changes

2023-10-27 12:44 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.scss
> +    width: 523px;
Pode deixar só com o width do botão, acredito que os demais estilos já pegam por padrão

2023-10-27 12:44 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.html
> +</section>
Estrutura ok. Sé terminar de estilizar mesmo.

Sobre os botões, falta sobrescrever as variáveis de estilo com a cor que tiver no figma:
- --mdc-filled-text-field-container-color
- --mdc-filled-text-field-input-text-color
- --mdc-filled-text-field-input-text-placeholder-color
- --mdc-filled-text-field-label-text-color

Listei algumas mas inspecionando o input dá pra pegar todas as variáveis que ele usa e testar.

OBS: Deixar elas no :root {} do **colors** ou do **themes** para poder ter efeito.

2023-10-27 12:44 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.ts
> +  getErrorMessage() {
Lembrar de documentar o método

2023-10-27 12:47 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.html
> +        <mat-error *ngIf="emailFormControl.hasError('email') && !emailFormControl.hasError('required')">
Precisa setar o pallette de **warn** no theme para poder trocar a cor dos erros. Se não surtir efeito, pode sobrescrever a variável também da mesma forma que feito com o Input.

2023-10-28 01:32 UTC, matheus-yudi-newrizon approved these changes

2023-10-28 01:35 UTC, merged