Feature/rr 269 front deploy app
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #12
Opened 2023-10-28 01:34 UTC by hernangior

pull request para correção em workflow

2023-10-31 01:32 UTC, matheus-yudi-newrizon requested changes

2023-10-31 01:32 UTC, matheus-yudi-newrizon commented on src/app/components/register-failed/register-failed.component.html
> +18:30
Como agora temos as telas do sistema, pode remover essas flags.

2023-10-31 01:32 UTC, matheus-yudi-newrizon commented on src/index.html
> +  <title>BoilerplateFrontendOrionBootcamp Teste* 18:36</title>
Mesmo caso da anterior

2023-11-01 12:43 UTC, hernangior commented on src/index.html
> +  <title>BoilerplateFrontendOrionBootcamp Teste* 18:36</title>
**Correção Aplicada**

a mensagem se tratava de teste de deploy, foi mantida na versão final incorretamente, já foi removida.

2023-11-01 12:45 UTC, hernangior commented on src/app/components/register-failed/register-failed.component.html
> +18:30
**Correção Aplicada**

O texto era uma verificação feita com outro componente da equipe durante processo de verificação, foi mantida no código enviado para commit incorretamente, sendo já resovlido o problema por correção do código.

2023-11-01 12:46 UTC, hernangior commented
**Correções solicitadas aplicadas**

Aguardando aprovação para que o PR possa ser aprovado e a rotina de deploy automático no GH Pages possa ser efetivada.

2023-11-01 12:52 UTC, hernangior commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] - Configurar o deploy da aplicação](https://trello.com/c/Fg8H0J8m/258-front-configurar-o-deploy-da-aplica%C3%A7%C3%A3o)

2023-11-02 00:52 UTC, matheus-yudi-newrizon approved these changes

2023-11-02 00:52 UTC, merged