Feature/rr 396 front ajustes pagina cadastro
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #16
Opened 2023-10-30 23:27 UTC by gabrieladnz

2023-10-30 23:28 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] Ajustes - Página de cadastro](https://trello.com/c/rGVvRXLE/396-front-ajustes-p%C3%A1gina-de-cadastro)

2023-10-31 02:58 UTC, matheus-yudi-newrizon requested changes

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on .github/workflows/angular-ghpages-abdo.yml
Esse arquivo veio do PR do Hernandez?

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.scss
> +.custom-btn:disabled {
Não seria bom setar o estilo global disabled também, igual fizemos com a label?

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.html
>        <mat-form-field class="example-full-width">
Agora que já está estilizado, seria bom estruturar e padronizar as classes de estilo dos componentes.

Para isso podemos, utilizar alguns padrões de nomeação/estilização. Indico o padrão/convenção **BEM**, é bem fácil de entender e apesar de verboso (gerar nomes extensos), ajuda a separar melhor os trechos do nosso HTML e facilita a estilização com SCSS.

Dá uma olhadinha sobre e qualquer dúvida me avisa por favor: 
- https://medium.com/trainingcenter/bem-em-5min-f5c80fd23439
- https://desenvolvimentoparaweb.com/css/bem/

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.ts
>          throw error;
Uma vez tratado o erro no bloco try/catch, não precisa dar um **throw** novamente.

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.ts
> +  public formValue(): void {
Poderia coolocar um nome mais explicativo no método... Algo como **persistFormValue** ou **storeFormValue**

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/home-page/home-page.component.html
Trocar o nome do componente.

A home page ainda será feita, então seria uma boa renomear esse componente para `register-page` e sua rota para algo **sign-up** ou **register**.

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/home-page/home-page.component.scss
> +@keyframes deslizar {
Manter o padrão de idioma para nomear o keyframe.

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/home-page/home-page.component.scss
> +@keyframes deslizarSubir {
Manter o padrão de idioma para nomear o keyframe.

2023-10-31 02:58 UTC, matheus-yudi-newrizon commented on src/index.html
> +  <title>BoilerplateFrontendOrionBootcamp Teste*</title>
Seria bom alterar não só esse title mas todas as referências ao **boilerplate** dentro do projeto:

![image](https://github.com/matheus-yudi-newrizon/review-reveal-web/assets/93654821/c4c0388b-7108-4fde-b6e5-f702aa1f6f74)

2023-10-31 03:01 UTC, gabrieladnz commented on .github/workflows/angular-ghpages-abdo.yml
Não.

2023-11-01 00:51 UTC, gabrieladnz commented on src/app/components/form-register/form-register.component.scss
> +.custom-btn:disabled {
Eu tentei, mas não está sendo aplicado.

2023-11-01 01:26 UTC, matheus-yudi-newrizon approved these changes

2023-11-01 01:27 UTC, merged