Feature/rr 406 front pop up solicita senha
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #19
Opened 2023-11-05 05:20 UTC by gabrieladnz

Obs: como o modal será chamado pela tela de login, que atualmente está sendo feita pelo Felipe, não estou subindo o código que abre o modal na tela.

2023-11-05 05:22 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] Checklist - Pop up de solicitação de recuperação de senha](https://trello.com/c/9Xh753WJ/406-front-checklist-pop-up-de-solicita%C3%A7%C3%A3o-de-recupera%C3%A7%C3%A3o-de-senha)

2023-11-07 02:20 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.scss
> +.modal__buttons {
Como estamos trabalhando com scss, dá pra usar hierarquia de estilos:
```
.modal {
    &__title {}
    &__input {}
    &__buttons {}
}
```

2023-11-07 02:25 UTC, matheus-yudi-newrizon requested changes

2023-11-07 02:25 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.scss
> +.modal__buttons {
Como estamos trabalhando com scss, dá pra usar hierarquia de estilos:
```
.modal {
    &__title {}
    &__input {}
    &__buttons {}
}
```

2023-11-07 02:25 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.ts
> +  emailPattern = /^[A-Za-z0-9.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
Sempre que possível colocar explícito o nível de acesso dos atrobutos (public | protected | private)

2023-11-07 02:25 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.ts
> +   * @returns
Pode deixar sem o @returns quando for **void**

2023-11-07 02:25 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.ts
> +        console.error("error: ", error);
Legal mostrar uma mensagem de erro mais descritiva

2023-11-07 02:25 UTC, matheus-yudi-newrizon commented on src/app/models/http/interface.ts
Realizar as melhorias de interface genérica e específica conforme conversamos.

2023-11-07 02:25 UTC, matheus-yudi-newrizon commented on src/app/services/user/user.service.ts
> +      return await lastValueFrom(this.httpClient.post<ReturnRead>('/forgot-password/', email))
Colocar o **BASE_URL** conforme conversamos

2023-11-07 02:35 UTC, matheus-yudi-newrizon requested changes

2023-11-07 02:35 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.ts
> +import { DialogData } from 'src/app/pages/register-page/register-page.component';
Está com erro nesse import

2023-11-07 02:35 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.ts
> +import { DialogData } from 'src/app/pages/register-page/register-page.component';
Está com erro nesse import

2023-11-07 02:37 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.ts
> +  forgotPasswordForm!: FormGroup;
Sempre que possível colocar explícito o nível de acesso dos atributos (public | protected | private)

2023-11-08 13:47 UTC, matheus-yudi-newrizon requested changes

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.html
> +  <button mat-button (click)="closeModal()">X</button>
Não seria melhor usar o ícone que está no figma?

https://www.figma.com/file/ELYLvQGdftC1x5yyTg4jq1/API-Imdb?node-id=92%3A7287&mode=dev

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/pages/login/checkbox/checkbox.component.ts
> +  openModalForgot(): void {
Documentar o método

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/pages/login/checkbox/checkbox.component.ts
> +    dialogRef.afterClosed().subscribe(() => {
Precisa desse log?

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/styles.scss
> +.custom__modal__forgotpassword {
Poderia deixar o nome da classe como ".custom__modal" apenas, aí daria para reutilizar no modal de how to play.

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/services/user/user.service.ts
> +}
Inserir uma linha entre a interface e a classe

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/services/user/user.service.ts
> +interface SuccessResponsePassword extends ReturnRead {
Essa interface acabou ficando igual a de baixo... a ideia não era extender a interface de Response base com especificando o atributo data?

Também, seria legal nomear seguindo o padrão da outra interface:

- **PasswordResetRequest** -> dados de envio para a API
- **PasswordResetResponse** -> dados de retorno da API

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/services/user/user.service.ts
> +interface ErrorResponsePassword extends ErrorResponse {
Como as interfaces de erro serão sempre iguais, não precisa criar uma específica, pode usar o ErrorRespsonse para tipar.

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/models/http/interface.ts
> +  message?: string;
Daria para termos só 2 interfaces bases de resposta nesse arquivo:

```ts
/** Interface de sucesso */
export interface SuccessResponse<DataType extends Record<string, unknown>> {
  success: boolean;
  data: DataType;
}

/** Interface de erro */
export interface ErrorResponse {
  success: boolean;
  message: string;
}
```

E as específicas de request/response ficam nos arquivos de service, igual você fez no user.service

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/services/user/user.service.ts
>      super(httpCliente);
Colocar o nome da variável em inglês

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.ts
> +  public emailPattern = /^[A-Za-z0-9.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
Poderia fazer de uma forme que seja possível reaproveitar essa regex no form-register e modal-forgot, talvez exportar uma const ou fazer um service...

2023-11-08 13:47 UTC, matheus-yudi-newrizon commented on src/app/components/modal-forgot-password/modal-forgot-password.component.ts
> +    if (!this.forgotPasswordForm.valid) {
Precisa desse método? Ele está retornando void sempre não?

2023-11-10 02:01 UTC, matheus-yudi-newrizon approved these changes

2023-11-10 02:01 UTC, merged