Feature/rr 261 front comunicacao api
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #2
Opened 2023-10-20 02:34 UTC by gabrieladnz

Desenvolvimento da camada de comunicação com a API.

2023-10-20 02:36 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] - Camada de comunicação com a API](https://trello.com/c/PODDUBbv/261-front-camada-de-comunica%C3%A7%C3%A3o-com-a-api)

2023-10-20 11:25 UTC, matheus-yudi-newrizon requested changes

2023-10-20 11:25 UTC, matheus-yudi-newrizon commented on src/app/services/request/request.service.ts
> +import { environment } from 'src/environments/environment.prod';
Lembra que mapeamos a troca de arquivos no momento de build lá no **angular.json** ?

![image](https://github.com/matheus-yudi-newrizon/review-reveal-web/assets/93654821/e9112ce1-3fce-4106-b0fc-2f3cb3157a36)

Então, o ideal é sempe consumir do **environment.ts**, já que ele vai ser substituído por outro arquivo de acordo com a flag de build informada.

2023-10-20 11:25 UTC, matheus-yudi-newrizon commented on src/app/services/request/request.service.ts
> +  private API: string = environment.baseUrl;
O que acha de seguir o nome da env na variável? Algo como **API_URL** ou **BASE_URL**

2023-10-20 11:25 UTC, matheus-yudi-newrizon commented on src/app/services/request/request.service.ts
> +export class RequestService {
Apesar de ainda não termos as rotas da API para consumir, seria legal estruturar essa classe de uma forma que ela seja reutilizável.

Sugestões:
- Criar interfaces bases para padronizar os retornos de CRUD (create, read, update, delete)
- Criar métodos para tratamento de erro, filtros, token
- Criar métodos genéricos de CRUD. Assim, quando existirem as rotas, bastaria criar um **service** que extenda o **RequestService** e automaticamente já teríamos os métodos herdados, precisando apenas alterar a rota que concatenada na URL base da API.
- Para ficar mais fácil de trabalhar com as requisições, seria bom converter os **Observables** do httpClient em **Promises** (legal dar uma olhadinha no material sobre [rxjs](https://rxjs.dev/deprecations/to-promise#conversion-to-promises) e [promises](https://medium.com/trainingcenter/entendendo-promises-de-uma-vez-por-todas-32442ec725c2)).

Exemplo de uso:
```ts
export class RequestService {
  protected BASE_URL: string = environment.baseUrl;

  constructor(protected httpClient: HttpClient) { }

  public create(data: TipoDoData): Observable<TipoRetorno> {
    return this.httpClient.post(this.BASE_URL, data);
  }

  public get(id: number): Observable<TipoRetorno> {
    return this.httpClient.get(`${this.BASE_URL}/${id}`);
  }
}

export class UserService extends RequestService {
  constructor(httpClient: HttpClient) {
    super(httpClient);

    // sobrescreve a URL da classe base
    this.BASE_URL += '/v1/users';
  }
}

export class ColorService extends RequestService {
  constructor(httpClient: HttpClient) {
    super(httpClient);

    // sobrescreve a URL da classe base
    this.BASE_URL += '/v1/colors';
  }
}

// na hora de chamar
export class SignInComponent {
  constructor(
    private userService: UserService,
    private colorService: ColorService,
  ) { }

  private createUserAndGetColor(): void {
    this.userService.create({ email: '', password: '' });
    this.colorService.get(1);
  }
}
```

2023-10-21 12:02 UTC, dairsposito commented on src/app/models/http/interface.ts
> +    user: string;
O user seria o próprio email?

2023-10-21 12:02 UTC, dairsposito commented on src/app/services/request/request.service.ts
> +      return await lastValueFrom(this.httpClient.get<Read>(`${this.BASE_URL}/${id}`));
Não ficou faltando concatenar o /user na rota, para indicar que é um usuário?

2023-10-21 16:57 UTC, matheus-yudi-newrizon requested changes

2023-10-21 16:57 UTC, matheus-yudi-newrizon commented on src/app/models/http/interface.ts
Confere por favor se a identação desse arquivo está no padrão dos demais. Deu a impressão de que está com um indent_size de 4 espaços

2023-10-21 16:57 UTC, matheus-yudi-newrizon commented on src/app/models/http/interface.ts
> +export interface Create {
Chegou a alinhar com o back sobre o padrão de resposta das rotas?

2023-10-21 16:57 UTC, matheus-yudi-newrizon commented on src/app/services/request/request.service.ts
> +  public async create(data: Create): Promise<Create> {
Sobre as interfaces, seria legal termos no mínimo 2 mapeadas, uma de entrada e uma de saída.

Por exemplo, em um fluxo de criação de usuário, o nosso formato de entrada seria algo como:

`
{
  email: string;
  password:  string;
}
`

e o retorno da API poderia ser o id do usuário criado:

`
{
  id: string;
}
`

2023-10-21 16:57 UTC, matheus-yudi-newrizon commented on src/app/services/request/request.service.ts
> +import { interval, firstValueFrom, lastValueFrom } from 'rxjs';
Está usando o **interval** e o **firstValueFrom** ?

2023-10-21 16:57 UTC, matheus-yudi-newrizon commented on src/app/services/request/request.service.ts
Ficou muito boa a classe e a documentação :clap:

2023-10-24 17:33 UTC, matheus-yudi-newrizon approved these changes

2023-10-24 17:33 UTC, merged

2023-10-24 17:36 UTC, dairsposito requested changes

2023-10-24 17:36 UTC, dairsposito commented on src/app/services/request/request.service.ts
> +      return await lastValueFrom(this.httpClient.get<Read>(`${this.BASE_URL}/${id}/${email}`));
Não há necessidade de incluir o email na rota de get do usuário, apenas o id

2023-10-24 17:36 UTC, dairsposito commented on src/app/services/request/request.service.ts
> +      return await lastValueFrom(this.httpClient.post<Create>(`${this.BASE_URL}/`, data));
Ficou faltando alinhar com o back a rota para deixar predefinido já