Feature/rr 394 front pagina de login
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #20
Opened 2023-11-05 23:16 UTC by felipeabdo

2023-11-06 13:38 UTC, felipeabdo commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] Checklist - Página de login](https://trello.com/c/ETMdWyVM/394-front-checklist-p%C3%A1gina-de-login)

2023-11-07 02:58 UTC, matheus-yudi-newrizon requested changes

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.html
> +  <!-- <button (click)="createAccount()" [disabled]="!registerForm.valid"  class="form__button form__button--disabled" mat-raised-button color="primary" type="submit">CREATE MY ACCOUNT</button> -->
Código comentado

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.scss
> +  // display: flex;
Código comentado

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/form-register/form-register.component.scss
> +::ng-deep .mat-mdc-form-field-error[_ngcontent-ng-c1679319657] {
Usar a hierarquia do scss para reaproveitar o seletor

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/navbar/navbar/navbar.component.scss
> +  // align-items: flex-start;
Código comentado

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/navbar/navbar/navbar.component.scss
> +
Identar o arquivo, removendo espaços em branco e formatação adequada.

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/navbar/navbar/navbar.component.ts
> +  currentRoute = '';
Sempre que possível colocar o nível de acesso do atributo (public, private, protected)

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/components/navbar/navbar/navbar.component.ts
> +  isSignUpPage() {
Documentar os métodos e corrigir a identação do arquivo

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/checkbox/checkbox.component.html
Precisa componentizar esse carinha? Como ele só vai ser utilizado nessa tela poderia ficar direto no html do login.

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/checkbox/checkbox.component.scss
Corrigir a identação do arquivo e removevr espaços em branco não necessários.

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/checkbox/checkbox.component.ts
Pode remover esse arquivo e colocar o checkbox direto no html do login

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.html
> +    <mat-error class="login-page__-width__error" *ngIf="emailFormControl.hasError('email') && !emailFormControl.hasError('required')">
Corrigir o nome da classe

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.html
> +    <mat-error class="login-page__-width__error" *ngIf="emailFormControl.hasError('required')">
Corrigir o nome da classe

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.html
> +    <input class="email login-page__width__email-input" type="email" matInput [formControl]="emailFormControl" placeholder="Ex. pat@example.com">
Vai ter esse placeholder?

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.scss
> +    &__button:active {
Daria para fazer:
```
&__button {
  &:hover {}
  &:active {}
}
```

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.scss
> +@use "@angular/material" as mat;
Corrigir a identação do arquivo

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.ts
> +  // encapsulation: ViewEncapsulation.None,
Código comentado

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.ts
> +export class LoginComponent {
Corrigir a identação, comentar os métodos, colocar o nível de acesso nos atributos e métodos

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/register-page/register-page.component.html
> +  <!-- <app-login></app-login> -->
Código comentado

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/register-page/register-page.component.ts
Pode desfazer as alterações desse arquivo

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/styles.scss
> +  --mdc-filled-text-field-input-text-placeholder-color: rgba(
Deixa em uma linha esse rgba

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/styles.scss
> +  --mdc-filled-text-field-label-text-color: var(--Gray-500, #6b6b83);
Essa variável existe? Se não, pode deixar direto a cor

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/styles.scss
> +    background-color: rgba(5, 5, 206, 0.356) !important;
O botão está azul... Pelo figma acredito que seja a cor (#6200EE)

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/styles.scss
> +  background: url(../src/assets/background/background.svg),
Deixar em uma linha

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/theme.scss
> +
Linha em branco

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/styles.scss
> +
Linha em branco

2023-11-07 02:58 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.ts
> +  }
O ideal seria já conversar com o pessoal do back para deixar feito a parte de comunicação, pelo menos com o service, a rota e os dados a serem enviados à API.

2023-11-08 13:53 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.html
> +      Email is <strong>required</strong>
* E-mail

2023-11-08 13:53 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.html
> +    <mat-label class="login-page__width__label">Email</mat-label>
*E-mail

2023-11-11 00:50 UTC, matheus-yudi-newrizon approved these changes

2023-11-11 00:56 UTC, merged