Feature/rr 565 front page inicio do jogo
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #25
Opened 2023-11-16 21:06 UTC by gabrieladnz

2023-11-16 21:07 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] Checklist - Tela da área acessada (início do jogo)](https://trello.com/c/DeJGouFl/565-front-checklist-tela-da-%C3%A1rea-acessada-in%C3%ADcio-do-jogo)

2023-11-18 02:41 UTC, matheus-yudi-newrizon requested changes

2023-11-18 02:41 UTC, matheus-yudi-newrizon commented on src/app/components/navbar/navbar/navbar.component.ts
> +  public isStarGamePage(): boolean {
*isStartGamePage

2023-11-18 02:41 UTC, matheus-yudi-newrizon commented on src/app/components/navbar/navbar/navbar.component.html
> +  <div class="navbar-page__right-icons" *ngIf="isLoginPage() || isStarGamePage()">
*isStartGamePage

2023-11-18 02:41 UTC, matheus-yudi-newrizon commented on src/app/components/navbar/navbar/navbar.component.html
> +    <a href="#" *ngIf="isSignUpPage() || isStarGamePage()" class="navbar-page__right-icons__logout">
*isStartGamePage

2023-11-18 02:41 UTC, matheus-yudi-newrizon commented on src/app/pages/login/login.component.ts
> +        this.router.navigate(['/start-game']);
Conforme conversamos, guardar o token para posterior uso na tela do jogo.

2023-11-18 17:03 UTC, matheus-yudi-newrizon approved these changes

2023-11-18 17:03 UTC, matheus-yudi-newrizon commented on src/app/services/token/token.service.ts
Ficou muito bom esse service :rocket:

2023-11-18 17:03 UTC, matheus-yudi-newrizon commented on src/app/services/token/token.service.ts
> +    localStorage.setItem(this.tokenUser, loginResponse.token);
Uma sugestão, poderia já receber direto só o valor do token. Aí na hora de chamar ficaria assim: `service.saveToken(loginResponse.token)`

2023-11-18 17:41 UTC, merged