Feature/rr 750 front pop up insucesso
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #38
Opened 2023-12-04 20:50 UTC by felipeabdo

2023-12-04 20:51 UTC, felipeabdo commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] Criação do pop up de insucesso - Guess movie [Tela do jogo]](https://trello.com/c/fUPgJXmX/750-front-cria%C3%A7%C3%A3o-do-pop-up-de-insucesso-guess-movie-tela-do-jogo)

2023-12-04 22:08 UTC, matheus-yudi-newrizon requested changes

2023-12-04 22:08 UTC, matheus-yudi-newrizon commented on src/app/components/pop-up-unsuccess-confirmation/pop-up-unsuccess-confirmation.component.ts
> +export class PopUpUnsuccessConfirmationComponent extends PopUpGameComponent {
Muito bom @felipeabdo :clap: 

Só precisa agora chamar esse componente na tela do game, onde a Gabi deixou a flag de TODO.

2023-12-07 00:13 UTC, matheus-yudi-newrizon approved these changes

2023-12-07 00:13 UTC, merged