Feature/rr 758 front tela confirmar email redefinir senha
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #39
Opened 2023-12-05 02:53 UTC by gabrieladnz

2023-12-05 02:53 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] Pop-up de redefinição de senha (Refinamento)](https://trello.com/c/3VprfOAT/758-front-pop-up-de-redefini%C3%A7%C3%A3o-de-senha-refinamento)

2023-12-06 02:34 UTC, matheus-yudi-newrizon requested changes

2023-12-06 02:34 UTC, matheus-yudi-newrizon commented on src/app/components/confirm-reset-password/confirm-reset-password.component.ts
> +  public override titlePageSuccess = 'A password reset request has been sent to your email';
Pra padronizar com o de baixo, pode deixar "e-mail"

2023-12-06 02:34 UTC, matheus-yudi-newrizon commented on src/app/app.module.ts
> +    ResetPasswordFailureComponent
Faltou uma vírgula no final da linha, ta estourando erro.

2023-12-06 02:34 UTC, matheus-yudi-newrizon commented on src/app/components/register-failed/register-failed.component.ts
> +  public override labelButton = 'RETURN TO HOME';
Pode deixar "RETURN" igual estava antes.

2023-12-06 02:34 UTC, matheus-yudi-newrizon commented on src/app/components/reset-password-failure/reset-password-failure.component.ts
> +  public override labelButton = 'RETURN TO HOME';
Pode deixar só "RETURN"

2023-12-06 02:34 UTC, matheus-yudi-newrizon commented on src/app/components/return-confirmation/return-confirmation.component.html
> +<section class="section-success">
Seria legal deixar com o contexto do componente, algo como "return-confirmation__section", "return-confirmation__icon-check"

2023-12-06 02:49 UTC, matheus-yudi-newrizon approved these changes

2023-12-06 02:49 UTC, merged