Feature/rr 263 front requisito senha
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #4
Opened 2023-10-23 21:26 UTC by gabrieladnz

2023-10-23 21:27 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] - Componente de requisitos de senha](https://trello.com/c/ZFCBQOZm/263-front-componente-de-requisitos-de-senha)

2023-10-25 03:31 UTC, matheus-yudi-newrizon requested changes

2023-10-25 03:31 UTC, matheus-yudi-newrizon commented on src/app/components/password-requirement/password-requirement.component.html
> +    <p [ngClass]="passwordSize ? 'valid' : 'invalid'">8 Characters</p>
Os ícones de check e error vão ser colocados depois?

2023-10-25 03:31 UTC, matheus-yudi-newrizon commented on src/app/components/password-requirement/password-requirement.component.html
> +  <div class="error" *ngIf="password.value">
Essa div não vai estar sempre visível?

2023-10-25 03:31 UTC, matheus-yudi-newrizon commented on src/app/components/password-requirement/password-requirement.component.ts
> +  samePassword = true;
Essas variáveis não serão `@Input` do componente? Seria legal ter um `@Output `também para a tela depois conseguir acessar o valor da senha.

https://angular.io/guide/inputs-outputs

2023-10-25 03:31 UTC, matheus-yudi-newrizon commented on src/app/components/password-requirement/password-requirement.component.ts
> +    } else {
Como o resultado da comparação é um booleano, daria para atribuir direto no `this.samePassword = password === confirmPassword`

2023-10-25 03:31 UTC, matheus-yudi-newrizon commented on src/app/components/password-requirement/password-requirement.component.html
> +    <p class="msg-error" *ngIf="!samePassword">Passwords do not match</p>
Seria legal disparar a comparação de senha também no input principal...

Imagina que eu digito uma senha válida e confirmo ela, mas altero a senha inicial, o que aconteceria com esse erro? Ele seria mostrado de novo?

2023-10-25 03:31 UTC, matheus-yudi-newrizon commented on src/app/services/password-validation/password-validation.service.ts
> +  passwordSize(password: string): boolean {
Apesar de sabermos que esse método é público, é legal sempre colocar o nível de acesso da função para ajudar na legibilidade: `public`, `protected` ou `private`.

Serve para as outras classes também.

2023-10-25 03:31 UTC, matheus-yudi-newrizon commented on src/app/services/password-validation/password-validation.service.ts
> +    const character = /[!@#$%^&*(),.?":{}|<>]/;
É legal validar com o pessoal do back também qual lista de caracteres especiais eles usaram, para padronizar.

2023-10-25 03:31 UTC, matheus-yudi-newrizon commented on src/app/components/password-requirement/password-requirement.component.html
> +    <input type="password" #password (input)="validatePassword(password.value)">
Seria bom já colocar o `<mat-form-field>` junto com a diretiva `matInput`, para seguir o layout do Input do material.

Com o mat-form-field, conseguimos colocar ícones, labels e mensagens de erros no input já estilizado: https://material.angular.io/components/form-field/overview#form-field-error

2023-10-25 03:38 UTC, gabrieladnz commented on src/app/components/password-requirement/password-requirement.component.html
> +    <p [ngClass]="passwordSize ? 'valid' : 'invalid'">8 Characters</p>
Sim, pelo Felipe

2023-10-25 04:30 UTC, gabrieladnz commented on src/app/components/password-requirement/password-requirement.component.html
> +  <div class="error" *ngIf="password.value">
Pensei em deixá-la visível somente quando o usuário inserisse a senha.

2023-10-26 02:46 UTC, matheus-yudi-newrizon approved these changes

2023-10-26 02:47 UTC, merged