Feature/rr 268 front configurar tema
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #6
Opened 2023-10-25 13:23 UTC by felipeabdo

2023-10-25 18:56 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] - Configurar tema da aplicação (fonts, cores, espaçamentos, ícones, logos)](https://trello.com/c/U2kZsdMI/268-front-configurar-tema-da-aplica%C3%A7%C3%A3o-fonts-cores-espa%C3%A7amentos-%C3%ADcones-logos)

2023-10-26 02:54 UTC, matheus-yudi-newrizon requested changes

2023-10-26 02:54 UTC, matheus-yudi-newrizon commented on angular.json
> +              // "node_modules/bootstrap/scss/bootstrap-grid.scss"
Remover o código comentado

2023-10-26 02:54 UTC, matheus-yudi-newrizon commented on src/app/app.component.html
> +
Remover linhas em branco

2023-10-26 02:54 UTC, matheus-yudi-newrizon commented on src/styles.scss
> +@import "../src/theme.scss";
Está importando o theme, mas não está usando as variáveis?

2023-10-26 02:54 UTC, matheus-yudi-newrizon commented on src/theme.scss
> +  50: white,
Vai ser tudo branco mesmo?

2023-10-26 02:54 UTC, matheus-yudi-newrizon commented on src/theme.scss
> +//   --mdc-filled-text-field-label-text-color: white;
Pode remover esse trecho comentado

2023-10-26 02:54 UTC, matheus-yudi-newrizon commented on src/app/pages/home-page/home-page.component.scss
> +// @import '../../../colors';
Remover código comentado

2023-10-26 02:54 UTC, matheus-yudi-newrizon commented on src/app/pages/home-page/home-page.component.scss
> +}
Remover esses testes de cor

2023-10-26 21:00 UTC, matheus-yudi-newrizon approved these changes

2023-10-26 21:00 UTC, merged