component: customização dos botões
matheus-yudi-newrizon/orion-bootcamp-front-boilerplate pull request #7
Opened 2023-10-25 18:48 UTC by felipeabdo

2023-10-25 18:55 UTC, gabrieladnz commented
![](https://github.trello.services/images/mini-trello-icon.png) [[FRONT] - Customização dos botões](https://trello.com/c/rC6V50vy/262-front-customiza%C3%A7%C3%A3o-dos-bot%C3%B5es)

2023-10-26 03:00 UTC, matheus-yudi-newrizon requested changes

2023-10-26 03:00 UTC, matheus-yudi-newrizon commented on src/app/app.component.scss
> +button {
A ideia é setar o estilo global dos botões definindo o tema pelo angular material ou então sobrescrevendo as variáveis que o botão do angular material usa (igual fizemos aquele dia procurando a variável e trocando o valor)

Esse código de sobrescrição e definição pode ficar no :root do styles ou então em um arquivo separado.

Deixando ele aqui, só vai funcionar no app.component.

2023-10-26 03:00 UTC, matheus-yudi-newrizon commented on src/app/app.component.html
> +    <button mat-flat-button color="primary">Primary</button>
Usar o botão só para testar o estilo aplicado, não precisa subir o código.

2023-10-26 21:17 UTC, closed without merging